### ISSUE TITLE
[mimir-distributed] Avoid series resharding during rolling ingester restart

### ISSUE THREAD

**Issue by Logiraptor** [grafana/helm-charts#1313]
As ingesters are restarted, their series are resharded onto other ingesters. During a rolling upgrade, this can lead to a lot of churn as series are resharded across virtually every ingester. 

Since we know the ingesters in this chart are deployed via a StatefulSet, we know the hostname and storage is stable across restarts. This means we could feasibly run with the following settings:

```
-distributor.extend-writes=false
-ingester.unregister-on-shutdown=false
```

If false, ingesters are not unregistered on shutdown and left in the ring with the LEAVING state. Setting to false prevents series resharding during ingesters rollouts, but requires to:
 1. Either manually forget ingesters on scale down or invoke the /shutdown endpoint
 2. Ensure ingester ID is preserved during rollouts

This is how we run Grafana Cloud, so it would make sense to me to bake this into the Helm Chart as well.

**Comment by 09jvilla** [comment]
As we evaluate this, we're discussing the possibility of removing `-distributor.extend-writes` completely.

**Comment by 09jvilla** [comment]
Related issue in Cortex filed by @bboreham about extend-writes.

**Comment by 09jvilla** [comment]
And we also have this one in Mimir: https://github.com/grafana/mimir/issues/92

**Comment by 09jvilla** [comment]
We set `-distributor.extend-writes` to `false` in Mimir 2.1 and we'll be removing it (leaving it permanently set to false) in 2 releases. 

Now the question is, do we set `-ingester.unregister-on-shutdown=false` in the Helm chart? We know that we may not want to do this in Mimir itself since we may not be able to make assumptions about stable hostname and storage, but we should be able to do this in the Helm chart where we deploy as a SS.
