### ISSUE TITLE
MountVolume.SetUp failed for volume "config" : configmap "loki-stack-promtail" not found

### ISSUE THREAD

**Issue by mckernanin** [grafana/helm-charts#2216]
I've had the loki-stack chart running for quite a while. Initially setup on chart version 2.5.0, upgraded to 2.8.9 a month ago. After a host reboot promtail didn't come back up. Tried updating to 2.9.9 today, and I'm still experiencing the same issue with promtail.

![image](https://user-images.githubusercontent.com/6300047/219488347-dd84652f-4cde-4f29-a20d-8aa3846fc11f.png)

These are the only configmaps I'm seeing:
![image](https://user-images.githubusercontent.com/6300047/219488407-65819dd8-a22b-471c-97b1-3ccf39269439.png)

I'm not sure what happened to this configmap?

**Comment by namantalaycha10** [comment]
this error is coming most probably because your configMap loki-stack-promtail not exist in the namespace
other reason can be [https://you.com/search?q=mountvolume.setup+failed+for+volume+configmap+not+found&tbm=youchat&cfr=chatb&chatQuery=&cid=c2_239dfca0-5548-40cd-bc8d-5cc2bcde014e](https://you.com/search?q=mountvolume.setup+failed+for+volume+configmap+not+found&tbm=youchat&cfr=chatb&chatQuery=&cid=c2_239dfca0-5548-40cd-bc8d-5cc2bcde014e)

**Comment by namantalaycha10** [comment]
this error is coming most probably because your configMap loki-stack-promtail not exist in the namespace
other reason can be [https://you.com/search?q=mountvolume.setup+failed+for+volume+configmap+not+found&tbm=youchat&cfr=chatb&chatQuery=&cid=c2_239dfca0-5548-40cd-bc8d-5cc2bcde014e](https://you.com/search?q=mountvolume.setup+failed+for+volume+configmap+not+found&tbm=youchat&cfr=chatb&chatQuery=&cid=c2_239dfca0-5548-40cd-bc8d-5cc2bcde014e)

**Comment by mckernanin** [comment]
Fixed after a reinstall
