### ISSUE TITLE
Chart 5.6.6/5.6.7/5.6.8 not working with helm-operator

### ISSUE THREAD

**Issue by pierluigilenoci** [grafana/helm-charts#23]
I tried to update with flux and helm-operator from 5.6.5 to 5.6.6 and, with the same values, I get this error:

`{"caller":"release.go:316","component":"release","error":"installation failed: template: grafana/templates/deployment.yaml:46:10: executing \"grafana/templates/deployment.yaml\" at \u003cinclude \"grafana.pod\" .\u003e: error calling include: template: grafana/templates/_pod.tpl:334:23: executing \"grafana.pod\" at \u003c$value\u003e: wrong type for value; expected string; got bool","helmVersion":"v3","phase":"install","release":"grafana","resource":"kube-infrastructure:helmrelease/grafana","targetNamespace":"kube-infrastructure","ts":"2020-09-17T13:18:15.184678561Z"}`

**Comment by pierluigilenoci** [comment]
Found the issue. This is the breaking change:
https://github.com/grafana/helm-charts/compare/grafana-5.6.5...grafana-5.6.7#diff-23cc34df6a30f48bbc4ecd1e462dce61

**Comment by pierluigilenoci** [comment]
@drc-agasser could you please take a look?

**Comment by drc-agasser** [comment]
There are no values included here to demonstrate the issue, but I'm guessing an environment variable value is being specified as a boolean:
```
env:
  MY_ENV_KEY: true
```
I would question how valid this is since environment variables are strings. However, since there is no documentation for how this data should appear other than `{}` and it worked before, this is a breaking change. I'll take a look at a way to resolve it.

In the meantime, a workaround would be to specify the env value as a string:
```
env:
  MY_ENV_KEY: "true"
```

**Comment by pierluigilenoci** [comment]
Thank you, guys! The problem is fixed. @drc-agasser @zanhsieh
