### ISSUE TITLE
loki-distributed helm chart nginx gateway basic authentication high CPU usage

### ISSUE THREAD

**Issue by tlaukkan** [grafana/helm-charts#243]
**Describe the bug**
Loki is deployed using Loki distributed helm chart. Enabling basic authentication causes order of magnitude higher CPU usage on gateway compared to normal loads on other components. 

**To Reproduce**
1. Deploy Loki using https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed
2. Executed any queries against API.
3. Observe gateway CPU usage

**Expected behavior**
Authenticating API requests takes order of magnitude less CPU.

**Suggested Fix**
1) Add support for sessions so that each requests do not need to authenticate again.

OR

2) Add configuration option to use plain text passwords in htpasswd to lower CPU usage on each authentication. 

stringData:
  .htpasswd: |
    {{ $.Values.gateway.basicAuth.username }}:{{ "{PLAIN}" }}{{ $.Values.gateway.basicAuth.password }}

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by unguiculus** [comment]
I don't think PLAIN text passwords should be used by default, sessions won't be possible at all and should not. The API is stateless. Sessions would involve cookies. I don't know if that would even help here.

The problem is probably that the `htpasswd` function used by the chart uses Bcrypt. I guess, this causes the high CPU usage. I think we can add an option to bring your own htpasswd as an alternative.

**Comment by unguiculus** [comment]
BTW, you can specify an existing secret for the basic auth creds. Would that be an option for you?
