### ISSUE TITLE
[grafana] extraVolumes not documented / examples for extraVolumeMounts not working

### ISSUE THREAD

**Issue by jan-mrm** [grafana/helm-charts#2777]
With pull request https://github.com/grafana/helm-charts/pull/2712 released in grafana chart version [grafana-6.61.2](https://github.com/grafana/helm-charts/releases/tag/grafana-6.61.2) the documentation does not match the required configuration anymore.
In that version up to the current version 7.0.3 `extraVolumes` is not a documented variable and the examples do not match the config anymore.
[values.yaml](https://github.com/grafana/helm-charts/blob/8411002c46dc32e97aa710ec686fdc86b68b874a/charts/grafana/values.yaml#L527C1-L545C49)
[configuration list](https://github.com/grafana/helm-charts/blob/grafana-7.0.3/charts/grafana/README.md#configuration)
[volume example](https://github.com/grafana/helm-charts/blob/8411002c46dc32e97aa710ec686fdc86b68b874a/charts/grafana/README.md#example-of-extravolumemounts)

**Comment by diversit** [comment]
Just upgrading chart from 6.57.4 to 7.0.4 and this breaks the deployment because the `extraVolumeMounts` are no longer added as a volume to the Deployment. The volume _is_ still added to the `volumeMounts` of the `grafana` container.

Looking at `helm show value grafana/grafana` it does not mention `extraVolumes` and this change is also not mentioned on the [chart page](https://github.com/grafana/helm-charts/tree/main/charts/grafana).

This seems to be a bug since `extraVolumes` is only used for adding a `volume` to the `Deployment` and `extraVolumeMounts` is only used for adding a `volumeMount` to the `grafana` container.

Expected: choose which property name to use and use this at _both_ locations: volumes and volumeMounts

Workaround: duplicate `extraVolumeMounts` as `extraVolumes`

**Comment by stephan2012** [comment]
Do you prefer to have `extraVolumeMounts` back in its original version or document `extraVolumes`, matching other charts?

See my proposal in https://github.com/stephan2012/grafana-helm-charts/commit/52c2ceb2658567f0c7644d5fb40bd7658b2473e0 that I can create a PR for if desired.

**Comment by jan-mrm** [comment]
I do not have any preference. I'd say that your documentation update would be good
