### ISSUE TITLE
[grafana] sensitive key is failing correct path

### ISSUE THREAD

**Issue by delia395** [grafana/helm-charts#2926]
Hi, 

I am installing prometheus-community/kube-prometheus-stack with grafana enabled. The helm install is failing. Config is like
`grafana:
  grafana.ini:
    auth.google:
      enabled: "true"
      client_id: "$__file{/etc/secrets/auth_generic_oauth/client_id}"
      client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}` 

I am getting error "Sensitive key 'auth.google.client_secret' should not be defined explicitly in values. Use variable expansion instead." with the example from README. 

It may likely due to an extra `\` in the regular expression [here](https://github.com/grafana/helm-charts/blob/04eb45b3e991e3982f8359fa5d6def008c4d20e7/charts/grafana/templates/_helpers.tpl#L266)

**Comment by bdalpe** [comment]
@delia395 It's not failing due to an extra slash. You'd get extra error output containing the following message: "... You can disable this client-side validation by changing the value of assertNoLeakedSecrets." 

What version of the `kube-prometheus-stack` chart are you using? The fixed version of the `grafana` chart is included with `kube-prometheus-stack` release `56.0.0` and above. See my comment here: https://github.com/grafana/helm-charts/issues/2899#issuecomment-1910314691

**Comment by delia395** [comment]
You are right as I was actually applying prometheus-community/kube-prometheus-stack 55.11.0! Glad to know it's resolved. Thank you for answering and supporting!
