### ISSUE TITLE
Why is the query-frontend a headless service?

### ISSUE THREAD

**Issue by kekscode** [grafana/helm-charts#405]
I read in the documentation at https://grafana.com/docs/loki/latest/architecture/#query-frontend:
_Query frontends are stateless. However, due to how the internal queue works, it’s recommended to run a few query frontend replicas to reap the benefit of fair scheduling. Two replicas should suffice in most cases._

In templates the service is set to headless though:
https://github.com/grafana/helm-charts/blob/loki-distributed-0.28.0/charts/loki-distributed/templates/query-frontend/service-query-frontend.yaml#L9

This means that - even when 1+n replicas are started (i have 2 running), only 1 of those two will be queried all the time (by LogCLI, Grafana, curl, ...), because having a headless service means no round robin load balancing between the pods behind the headless service.

Would it be an improvement to change this or is there something i'm missing here?
Maybe @unguiculus has an idea?

**Comment by mehta-ankit** [comment]
we have the same question. Any idea as to why ?
Can we contribute a change to make it a non headless service with removing the clusterIP: None key.

**Comment by ryanprobus** [comment]
I think its a headless service because the gateway uses [kube-dns](https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml#L10) as the resolver. With a headless service, multiple IP addresses should be returned for the DNS lookup (one for each pod the service selects) and according to this [nginx documentation](https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/#configuring-http-load-balancing-using-dns), when the upstream is resolved to multiple IP addresses, traffic is distributed round-robin style by default.
