### ISSUE TITLE
symlink in repo prevents charts import in rancher

### ISSUE THREAD

**Issue by styk-tv** [grafana/helm-charts#502]
Maybe not feature that everyone is looking for but it would be good to not have symlinks in chart repos.  It seems to be a bad practice anyways.

Upon installation on grafana charts in new Rancher 2.5.7 there is an error message
<img width="1049" alt="Screenshot 2021-06-16 at 13 49 32" src="https://user-images.githubusercontent.com/838921/122222428-29718600-ceaa-11eb-84d2-cd8a080e013e.png">

With the blame of
<img width="953" alt="Screenshot 2021-06-16 at 13 50 57" src="https://user-images.githubusercontent.com/838921/122222451-2eced080-ceaa-11eb-8d33-658b709071dc.png">

Would be great if this matters to anyone.
CC: @jdbaldry 

Cheers.

**Comment by jdbaldry** [comment]
I wasn't aware that this would cause an issue with Rancher, thanks for raising this issue. The symlink in question isn't used and is just an artifact of backwards compatible changes made in [jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler). I should be able to remove this and add an ignore so that it won't be recommitted.

**Comment by styk-tv** [comment]
confirming `jdb/remove-symlink` branch restored the catalog
many thanks @jdbaldry 

<img width="1386" alt="Screenshot 2021-06-17 at 07 46 29" src="https://user-images.githubusercontent.com/838921/122345901-46f12f00-cf40-11eb-9e88-5e9bc885de8d.png">
