### ISSUE TITLE
[fluent bit] Use the official chart as dependency and don't deprecate the Grafana version here

### ISSUE THREAD

**Issue by sherifkayad** [grafana/helm-charts#514]
I was doing a regular update of the Loki stack when I noticed that the fluent bit chart here in the Grafana repo is marked as deprecated in favor of the original official chart.

Of course I attempted to configure the official chart at https://github.com/fluent/helm-charts and install it instead of the one here

## Problems faced with the switch:
- Couldn't help but notice that there is a significant effort required to make the original chart configs behave as the one generated by the Grafana Helm chart
- At the end with the official Docker Image of Fluent Bit I wasn't able to get the Loki plugin behave as I wanted .. For example:
-- The documentation of configurations the official Loki plugin https://docs.fluentbit.io/manual/pipeline/outputs/loki is different from the Grafana custom build https://grafana.com/docs/loki/latest/clients/fluentbit/
-- The labels extraction / mapping is working differently (no map.json file is possible in the official plugin)
-- I wasn't successful with removing the keys that are already in the labels from the log (e.g. the `kubernetes` JSON object and the `stream`)
-- Overall had the feeling that the Grafana Docker build of Fluent Bit (grafana/fluent-bit-plugin-loki) is way superior to the official Fluent Bit build (fluent/fluent-bit) when it comes to the Loki output configuration and end behavior

## How I currently fixed it?
- Basically I used the official Chart from fluent bit, however, I used the custom image from Grafana (e.g. with version 2.2.1-amd64)
- The Loki output part is configured following the Grafana way not the official plugin way => https://grafana.com/docs/loki/latest/clients/fluentbit/

## Proposal
- I would like to propose to use the official Chart as a dependency to a Grafana chart that would act as a child and override the needed values there
- Among the overriden values will be of course the Image part as well as a standard configuration that can act as guidance to people
- People interested in using Fluent Bit with Loki can use the Chart in this repo here instead of the official chart
- That being said, let's not deprecate this amazing Chart here!

I am happy to work on a PR to achieve this. Let me know what you think.

**Comment by sherifkayad** [comment]
@Whyeasy Your feedback is much appreciated

**Comment by Whyeasy** [comment]
Hi,

Thanks for your feedback regarding this chart. We discussed deprecating this chart with several maintainers and we had following reasons to deprecate the chart:

- This repo should contain Helm Charts for Grafana products only.
- Now the focus in improving a chart is in one location and the whole community can benefit from this.
- There was no maintainer who was taking ownership of this chart, resulted in long outstanding PRs.

---
`Basically I used the official Chart from fluent bit, however, I used the custom image from Grafana (e.g. with version 2.2.1-amd64)` This one was known and the quickest migration to the new chart. I think the Official plugin is not GA yet and is still being worked. Until that time we advice to use the Grafana image.

I would advice to create PRs in the official chart instead of this one, this way everybody who uses Fluent Bit will enjoy these improvements.

@unguiculus did I miss anything?

**Comment by sherifkayad** [comment]
@Whyeasy Got ya. Thanks for the prompt feedback. Two questions:
- How can I follow the status of the official plugin reaching GA? .. There's no indicator whatsoever about its current state
- Do you plan to keep maintaining the custom build forever or is that only until the official plugin stabilizes? .. I can see that the work done on the official plugin is mainly influenced by the Grafana work, however, as I said some configs are different .. or to formulate that accurately: the configs are following a different naming convention

**Comment by Whyeasy** [comment]
`How can I follow the status of the official plugin reaching GA? .. There's no indicator whatsoever about its current state` - Don't know sorry.

Regarding the image I also don't know, that's a question the Loki developers can answer.

**Comment by sherifkayad** [comment]
Thanks though .. I will be closing this ticket here
