### ISSUE TITLE
Notification Channels missing from .yaml on Upgrade to 8.3.2

### ISSUE THREAD

**Issue by ljonka** [grafana/helm-charts#910]
After Upgrading grafana image from 8.1.x to 8.3.2 the notification channels are not available anymore, the provisioning yaml file is beeing loaded by sidecar successfully and is available in grafana container but have no effect in alerts menu.

As a temporary fix a downgrade to 8.2.7 helped. 

Did the syntax or path changed in 8.3.x somehow for notifications?

Thanks

**Comment by Reinhard-F** [comment]
We have the same Problem, so we update to the latest version (with helm chart 30.0.0) to version 8.3.4. But the error is still there:
When i use https://mygrafana.test/alerting/list i see the default rules, but not my custom rules.
When i use https://mygrafana.test/alerting/notifications i see the default "grafana-default-email" contact, but not my custom contacts.

When i use the api it looks different:
Under https://mygrafana.test/api/alerts i can see my custom alerts.
Under https://mygrafana.test/api/alert-notifications/ i can see my custom notifications.

We activate the debug log and checked the log entries:
lvl=dbug msg="Parsing alert notifications provisioning file" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers file.Name=notifiers.yaml
No error can be seen here either.

It looks like this is a display problem.

Is a solution already available for this error?

**Comment by upstream-dmahlberg** [comment]
Unified alerting apparently uses another API Endpoint: /api/alertmanager/grafana/config/api/v1/alerts

I've come to believe that this might be due to [Grafana 8.3 automatically switching users over to the new unified alerting system](https://grafana.com/docs/grafana/latest/alerting/). I have opened a question in the [Grafana Community board](https://community.grafana.com/t/configuring-unified-alerts-in-kubernetes-using-the-helm-chart/58981) regarding the configuration of the unified alert system (which apparently uses a built-in alertmanager now, see [the intro webinar](https://grafana.com/go/webinar/intro-to-unified-alerting-in-grafana/).

**Comment by upstream-dmahlberg** [comment]
I've found _some_ rudimentary API documentation here: https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/index.html

**Comment by via-justa** [comment]
Looking forward to seeing some progress on that issue.
Did anyone manage to find a workaround until the issue is resolved?

**Comment by Reinhard-F** [comment]
We are still using Grafana Version 8.2.7, because migration of our notifications and alerts is still not working.

We try to set this keys in our values.yaml: https://www.42.mach7x.com/2022/01/05/enable-opt-in-grafana-unified-alerting-in-your-values-yaml/
According to the documentation it should work: https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/

With version 8.2.7 we are able to use configmaps which contain the dashboards (with their alerts). These are loaded when the pod starts. This no longer works under version 8.3.X. Since we cannot recreate the notifications and alerts every time the pod is restarted, we urgently need to load them when the pod starts. Unfortunately I haven't found a way for this with version 8.3.X ...

**Comment by cbernard-psee** [comment]
How can we progress on this issue? This is really gating to keep managing alerts as code

**Comment by kjwierenga** [comment]
I'm using Grafana 8.3 in k8s via kube-prometheus-stack helm chart. Can't upgrade just yet.

The workaround that worked for me is to set the following env variables:

```env
GF_UNIFIED_ALERTING_ENABLED=false 
GF_ALERTING_ENABLED=true
```

For reference: I found this fix [here](https://github.com/zulip/zulip/issues/20087#issuecomment-1065074508).

**Comment by sivadeepN** [comment]
Did anyone find a solution for this. According to documentation upgrade from a legacy alerting system to a unified alerting systems should migrate notification channels to contact points but this is not happening. I only see a default point. However when I hit the old API  [ https://mygrafana.test/api/alert-notifications/ ](https://mygrafana.test/api/alert-notifications/)  I can see all the  contact points.
